### ISSUE TITLE
no file webui.cmd

### ISSUE THREAD

**Issue by opensourcefan2** [Woolverine94/biniou#28]
After install there was no webui.cmd found on my PC.

**Comment by Woolverine94** [comment]
Hello @opensourcefan2,

Thanks for you feedback. 

Webui.cmd is pulled by the git clone command and is unlikely to miss at the end of the install process, unless the install dramatically fails : 

  - Did you see any error message during install process ?   
  - Did your Antivirus reports something (cmd files could seems suspicious to some AV) ? 
  - Did a biniou directory has been created in your %userprofile% directory ? 

Anyway, you can find this file [here](https://raw.githubusercontent.com/Woolverine94/biniou/main/webui.cmd) -right-click and "save as"- and copy it inside the biniou directory if it's the only missing file.

I close this issue as it seems to be an A/V or install problem on your side, but don't hesitate to re-open it and add more details about your setup if required.

Thanks again for reporting.

**Comment by opensourcefan2** [comment]
Thanks for your answer. I first installed via installer, then I tried via the batch file. The installation with batch file added more files to the biniou folder, but the folder still only have 3 other folder in it, nothing else. The provided file in your answer didnt help. Both setups went without an error as far as I saw. I dont have an AV (just the Microsoft thingy). I added a pic of the folder.
![Unbenannt](https://github.com/user-attachments/assets/ebb77d7b-cbbc-4c5b-af7f-fe7be96ec55c)

**Comment by Woolverine94** [comment]
@opensourcefan2 

You can't reinstall over an existing biniou directory. 
You have to delete the existing biniou directory after a faulty install and relaunch the installer. 
Please note that it is not necessary to uninstall the requirements (git, python, etc), they will be handled automatically by the install script.
Please also note that the .exe installer only pull the .cmd file installer and launch it, so you can use either the exe or cmd file, result should be the same. 
You should have way more file in this folder than the 4 folders and webui.cmd after the git clone step. 
Please also note that biniou takes some time to deploy after installing the requirements and deploy a lot of pip packages.

I think that you probably encountered an error at the first install during the git clone step and everything that happened after was doomed to fail, because the broken biniou folder still exists.

Thanks for your interest in biniou and don't hesitate if you still need some help to install.
