### ISSUE TITLE
Error when running Docker image (MacOS)

### ISSUE THREAD

**Issue by lepicodon** [Woolverine94/biniou#42]
**Describe the bug**
Docker image doesn't run with an error with gradio (see screenshot)

**To Reproduce**
Followed instructions...
`
docker build -t biniou https://github.com/Woolverine94/biniou.git
`
OK

`
docker run -it --restart=always -p 7860:7860 \
-v biniou_outputs:/home/biniou/biniou/outputs \
-v biniou_models:/home/biniou/biniou/models \
-v biniou_cache:/home/biniou/.cache/huggingface \
-v biniou_gfpgan:/home/biniou/biniou/gfpgan \
biniou:latest
`
Got the error here

**Expected behavior**
WebUI (app) not running

**Console log**
see screenshot...

**Hardware (please complete the following information):**
- MacBookPro M3 Pro (18GB RAM)
- MacOS Sonoma 14.6.1

**Screenshot**
<img width="1397" alt="biniou-error" src="https://github.com/user-attachments/assets/931c495b-7812-43ef-adfa-3884021b9677">

Merci d'avance pour ton aide, ton projet a l'air sympa ! :-)

**Comment by Woolverine94** [comment]
Hello @lepicodon,

Thanks for your report and your interest in the project. 

You're opening the first issue on MacOS (congratulations !), and I've few experience on it, but the error message seems pretty clear to me : gradio is not installed. 

It is normally deployed at step "[7/9] RUN ./install.sh" in your screenshot. 

There's not a lot of reasons for which it can't be installed, so I bet on a download problem that is not logged by . 

Can you try to : 
  - Delete the created image
  - Recreate the image using the following command : `docker build --no-cache --progress=plain -t biniou https://github.com/Woolverine94/biniou.git 2>&1 | tee build.log` (hope it works on MacOS). 

If the error is still here, then post the detailed "build.log" file that should be created during install. 

> Merci d'avance pour ton aide, ton projet a l'air sympa ! :-)

Avec plaisir et merci pour cette appréciation de mon travail !

**Comment by lepicodon** [comment]
Same error without cache... it seems to download gradio tho.
Attached is the log file if it helps you locate the issue.

Merci !!
[build.log](https://github.com/user-attachments/files/16825683/build.log)

**Comment by Woolverine94** [comment]
@lepicodon 

Thanks for your feedback. 

Got it : it has nothing to do with gradio itself,  the installer stops after failing to deploy exiv2 and never installs other dependencies, including gradio :

```bash
#9 67.12   Downloading exiv2-0.17.0.tar.gz (1.6 MB)
#9 67.22      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.6/1.6 MB 16.0 MB/s eta 0:00:00
#9 67.29   Installing build dependencies: started
#9 68.30   Installing build dependencies: finished with status 'done'
#9 68.30   Getting requirements to build wheel: started
#9 68.35   Getting requirements to build wheel: finished with status 'error'
#9 68.35   error: subprocess-exited-with-error
#9 68.35   
#9 68.35   × Getting requirements to build wheel did not run successfully.
#9 68.35   │ exit code: 1
#9 68.35   ╰─> [2 lines of output]
#9 68.35       [Errno 2] No such file or directory: 'pkg-config'
#9 68.35       ERROR: No SWIG source for libexiv2 version None
#9 68.35       [end of output]
#9 68.35   
#9 68.35   note: This error originates from a subprocess, and is likely not a problem with pip.
#9 68.37 error: subprocess-exited-with-error
#9 68.37 
#9 68.37 × Getting requirements to build wheel did not run successfully.
#9 68.37 │ exit code: 1
#9 68.37 ╰─> See above for output.
#9 68.37 
#9 68.37 note: This error originates from a subprocess, and is likely not a problem with pip.
```

Processor's architecture is probably the origin of this problem, and much likely the same as described in issue #39. Sorry for that, I completely forgot that MacOS could be aarch64 now. 

Unfortunately, according to @KintCark, it's only the first error of a long list ...  

It's a bad news, because it means that biniou is definitely incompatible with Apple silicon, regardless of the installation method. 

But, thanks to your tests, I know it now, so  ... thanks a lot anyway ! I will update the documentation to reflect this.

Only thing I can suggest is installing biniou in a virtual machine that emulate an AMD64 CPU (which should work) but I'm not sure at all it is doable on Apple silicon. 

I'm closing this issue, as there is no solutions at my level. Really sorry for that. 

... et désolé pour le temps perdu :(

**Comment by lepicodon** [comment]
Thank you for the explanation!
I'll try to run it another way (VM or other).

**Comment by lepicodon** [comment]
I was able to run Biniou using a Linux VM with OrbStack!
You can specify the proc architecture when creating the box so by selecting Intel it worked :)

<img width="330" alt="orbstack-VM" src="https://github.com/user-attachments/assets/6ab129c4-585c-4a36-9aa4-dae822f70d84">

I can play with Biniou now!

**Comment by Woolverine94** [comment]
@lepicodon,

Woow ! Thanks for the tip ! 

Really happy to see there is a workaround for MacOS users ! 

I had this to the documentation and gives you proper credits. 

Merciiiiii !
